fixed 'null is not an object (evaluating 'this._map.containerPointToLayerPoint')'
maplibre/maplibre-gl-leaflet pull request #59
Opened 2024-07-08 12:16 UTC by smeyer-p2er

2024-07-15 14:21 UTC, ianthetechie requested changes
Thanks for your PR @smeyer-p2er! Content-wise this looks good to me. Just one minor nit with formatting.

Two quick things to streamline future contributions:

* Could you enable maintainer edits on your PRs? That way we can make these changes and merge faster!
* You can add "Closes # ..." to your PR description to auto-close issues too!

2024-07-15 14:21 UTC, ianthetechie commented on leaflet-maplibre-gl.js
> +              }
```suggestion
            }
```

2024-07-16 07:33 UTC, smeyer-p2er commented
Thanks for your review. I'm not sure how to enable "maintainer edits" .

2024-07-16 08:05 UTC, ianthetechie approved these changes

2024-07-16 08:12 UTC, ianthetechie commented
@lseelenbinder can you merge + push this? Looks like I don't have write access ;)

2024-07-16 08:44 UTC, lseelenbinder approved these changes
LGTM. Thanks!

2024-07-16 08:44 UTC, merged